# site properties and page defaults
title: Neural Systems Lab
subtitle: 
description: An engaging 1-3 sentence description of your lab.
header: images/nsl.jpg
footer: images/nsl.jpg
proofer: false

# site social media and other links
links:
  email: rao@cs.washington.edu
  github: Neural-Systems-Lab
  youtube: uwneuralsystems

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_press
  - scope:
      type: "press"
    values:
      layout: post
  # markdown files in /_news
  - scope:
      type: "news"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  press:
    output: true
  # generate page for each news item
  news:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
